/* ==========================================================================
   Gestão do TOP — módulo do sistema Missão Revolução
   Carregado ANTES do script principal (só declara funções; usa S, render, popup etc. em tempo de execução).
   Dados em S.top[projetoId] = { setores, familias, veiculos, participantes, importacoes, saudeAcesso, config }
   ========================================================================== */
'use strict';
const TOP_TIPOS = { novato: 'Novato', servidor: 'Servidor', coord: 'Coordenação' };
const TOP_SETORES_PADRAO = ['Coordenação Geral', 'Segurança', 'Eventos', 'Logística', 'Alimentação', 'Intercessão', 'Mídia', 'Voz', 'ADM', 'Resgate', 'Hakuna', 'DOC', 'Tempo e Execução', 'Comunicação'];
let topProj = null, topF = { q: '', setor: '', cidade: '', sit: '', fam: '', veic: '', tipo: '' };

function topDe(pid) {
  S.top = S.top || {}; if (!S.top[pid]) S.top[pid] = { setores: TOP_SETORES_PADRAO.map(n => ({ id: uid(), nome: n, meta: 0 })), familias: [], veiculos: [], participantes: [], importacoes: [], saudeAcesso: [] };
  const t = S.top[pid]; t.setores = t.setores || []; t.familias = t.familias || []; t.veiculos = t.veiculos || []; t.participantes = t.participantes || []; t.importacoes = t.importacoes || []; t.saudeAcesso = t.saudeAcesso || []; return t;
}
const topProjetoAtual = () => { const ps = S.projetos.filter(p => p.ativo !== false); if (!ps.length) return null; if (!topProj || !ps.some(p => p.id === topProj)) topProj = ps[0].id; return ps.find(p => p.id === topProj); };
const tpNome = (p) => esc(p.nome); const tpCurto = (p) => esc((p.nome || '').split(' ').slice(0, 2).join(' '));
const tpById = (t, id) => t.participantes.find(p => p.id === id);
const intercDe = (x) => x.intercessores || (x.intercessorId ? [x.intercessorId] : []);
const minInterc = (t) => Number((t.config || {}).minIntercessores) || 2;
const semInterc = (t, ns) => ns.filter(x => intercDe(x).length < minInterc(t));
function podeVerSaude(p) { const u = me(); const pap = papelU(u); if (['presidente', 'tesoureiro'].includes(pap)) return true; if (p && (p.coordenadorId === u.id || p.admId === u.id)) return true; const t = p && topDe(p.id); return !!(t && t.saudeAcesso.includes(u.id)); }
function podeEditarTop(p) { const u = me(); const pap = papelU(u); return ['presidente', 'tesoureiro', 'secretario', 'vice', 'diretor_financeiro'].includes(pap) || (p && (p.coordenadorId === u.id || p.admId === u.id)); }

// ------------------------------------------------------------ página
function pgTop() {
  const p = topProjetoAtual();
  const cab = heading('Gestão do TOP', 'Inscritos importados do Legendários Global, alocação em setores, famílias, embarque, lista de oração e saúde — um cadastro por projeto.');
  if (!p) return cab + '<div class="card empty">Nenhum projeto ativo. Cadastre o TOP em Projetos → Cadastro de projetos.</div>';
  const t = topDe(p.id); const s = sub.top || 'painel';
  const sel = `<div class="flex noprint" style="margin:-6px 0 10px"><label class="flex sm" style="margin:0">TOP / projeto <select style="width:auto" onchange="topProj=this.value;render()">${S.projetos.filter(x => x.ativo !== false).map(x => `<option value="${x.id}" ${x.id === p.id ? 'selected' : ''}>${esc(x.nome)}</option>`).join('')}</select></label><span class="sm mut">${p.data ? 'data ' + dd(p.data) + ' · ' : ''}${t.participantes.length} inscrito(s)${t.importacoes.length ? ' · última importação ' + dt(t.importacoes[t.importacoes.length - 1].em) : ''}</span></div>`;
  const abas = [['painel', 'Painel'], ['novatos', 'Novatos', t.participantes.filter(x => x.tipo === 'novato').length], ['servidores', 'Servidores'], ['setores', 'Setores', t.participantes.filter(x => x.tipo !== 'novato' && !x.setorId).length], ['familias', 'Famílias'], ['embarque', 'Embarque'], ['oracao', 'Lista de oração'], ['saude', 'Saúde e resgate'], ['linha', 'Linha do tempo'], ['importar', 'Importar / cadastro']];
  const V = { painel: topPainel, novatos: topNovatos, servidores: topServidores, setores: topSetores, familias: topFamilias, embarque: topEmbarque, oracao: topOracao, saude: topSaude, linha: topLinha, importar: topImportar };
  return cab + sel + tabs('top', abas, 'painel') + (V[s] || topPainel)(p, t);
}
const topFiltrar = (t, lista) => lista.filter(x => (!topF.q || [x.nome, x.cidade, x.igreja, x.sede, x.email].join(' ').toLowerCase().includes(topF.q.toLowerCase())) && (!topF.cidade || x.cidade === topF.cidade) && (!topF.setor || (topF.setor === '__sem' ? !x.setorId : x.setorId === topF.setor)) && (!topF.fam || (topF.fam === '__sem' ? !x.familiaId : x.familiaId === topF.fam)) && (!topF.veic || (topF.veic === '__sem' ? !x.veiculoId : x.veiculoId === topF.veic)) && (!topF.tipo || x.tipo === topF.tipo) && (!topF.sit || (topF.sit === 'inapto' ? x.saude && x.saude.avaliacao && x.saude.avaliacao !== 'Apto' : topF.sit === 'presente' ? x.status === 'PRESENTE' : topF.sit === 'ausente' ? x.status !== 'PRESENTE' : true)));
function topBarra(t, lista, opts) {
  const w = 'style="width:auto;padding:6px 8px;font-size:12.5px"'; const set = (k) => `onchange="topF.${k}=this.value;render()"`;
  return `<div class="flex noprint" style="gap:6px;flex-wrap:wrap;margin-bottom:10px;align-items:center"><input ${w.replace('width:auto', 'width:220px')} placeholder="buscar nome, cidade, igreja" value="${esc(topF.q)}" oninput="topF.q=this.value" onchange="render()">
    <select ${w} ${set('cidade')}><option value="">cidade: todas</option>${[...new Set(lista.map(x => x.cidade).filter(Boolean))].sort().map(c => `<option ${topF.cidade === c ? 'selected' : ''}>${esc(c)}</option>`).join('')}</select>
    ${opts.setor ? `<select ${w} ${set('setor')}><option value="">setor: todos</option><option value="__sem" ${topF.setor === '__sem' ? 'selected' : ''}>sem setor</option>${t.setores.map(s => `<option value="${s.id}" ${topF.setor === s.id ? 'selected' : ''}>${esc(s.nome)}</option>`).join('')}</select>` : ''}
    ${opts.fam ? `<select ${w} ${set('fam')}><option value="">família: todas</option><option value="__sem" ${topF.fam === '__sem' ? 'selected' : ''}>sem família</option>${t.familias.map(f => `<option value="${f.id}" ${topF.fam === f.id ? 'selected' : ''}>${esc(f.nome)}</option>`).join('')}</select>` : ''}
    ${opts.tipo ? `<select ${w} ${set('tipo')}><option value="">tipo: todos</option>${Object.entries(TOP_TIPOS).map(([k, v]) => `<option value="${k}" ${topF.tipo === k ? 'selected' : ''}>${v}</option>`).join('')}</select>` : ''}
    <select ${w} ${set('sit')}><option value="">situação: todas</option><option value="presente" ${topF.sit === 'presente' ? 'selected' : ''}>credenciados</option><option value="ausente" ${topF.sit === 'ausente' ? 'selected' : ''}>não credenciados</option><option value="inapto" ${topF.sit === 'inapto' ? 'selected' : ''}>não aptos</option></select>
    ${Object.values(topF).some(Boolean) ? `<button class="link" style="padding:4px 6px" onclick="topF={q:'',setor:'',cidade:'',sit:'',fam:'',veic:'',tipo:''};render()">limpar</button>` : ''}<span class="right"></span>${opts.novo ? `<button class="p" onclick="popupParticipante('${opts.novo}')">+ ${TOP_TIPOS[opts.novo]}</button>` : ''}<button class="s" onclick="topExportar('${opts.csv || 'lista'}')">CSV</button><button class="s" onclick="print()">Imprimir</button></div>`;
}
const selSetor = (t, x) => `<select onchange="topSet('${x.id}','setorId',this.value)"><option value="">— sem setor —</option>${t.setores.map(s => `<option value="${s.id}" ${x.setorId === s.id ? 'selected' : ''}>${esc(s.nome)}</option>`).join('')}</select>`;
const selFam = (t, x) => `<select onchange="topSet('${x.id}','familiaId',this.value)"><option value="">—</option>${t.familias.map(f => `<option value="${f.id}" ${x.familiaId === f.id ? 'selected' : ''}>${esc(f.nome)}</option>`).join('')}</select>`;
const selVeic = (t, x) => `<select onchange="topSet('${x.id}','veiculoId',this.value)"><option value="">— a definir —</option>${t.veiculos.map(v => `<option value="${v.id}" ${x.veiculoId === v.id ? 'selected' : ''}>${esc(v.nome)}</option>`).join('')}</select>`;
const pillSit = (x) => x.status === 'PRESENTE' ? '<span class="pill ok">credenciado</span>' : '<span class="pill grey">inscrito</span>';
const pillRisco = (x) => { const r = x.saude && x.saude.risco; const av = x.saude && x.saude.avaliacao; if (av && av !== 'Apto') return `<span class="pill red">${esc(av)}</span>`; return r ? `<span class="pill ${r === 'Baixo' ? 'ok' : r === 'Médio' ? 'warn' : 'red'}">${esc(r)}</span>` : ''; };
function topSet(id, k, v) { const p = topProjetoAtual(); const t = topDe(p.id); const x = tpById(t, id); if (!x) return; x[k] = v || null; x.alteradoEm = agora(); save(); render(); }
function topExportar(nome) { const p = topProjetoAtual(); const t = topDe(p.id); const cols = ['tipo', 'nome', 'email', 'telefone', 'cidade', 'sede', 'igreja', 'idade', 'camisa', 'status', 'setor', 'familia', 'veiculo', 'intercessor']; const nomeS = (x) => (t.setores.find(s => s.id === x.setorId) || {}).nome || '', nomeF = (x) => (t.familias.find(f => f.id === x.familiaId) || {}).nome || '', nomeV = (x) => (t.veiculos.find(v => v.id === x.veiculoId) || {}).nome || '', nomeI = (x) => intercDe(x).map(id => (tpById(t, id) || {}).nome || '').join(' / '); const linhas = [cols.join(';')].concat(topFiltrar(t, t.participantes).map(x => [TOP_TIPOS[x.tipo], x.nome, x.email, x.telefone, x.cidade, x.sede, x.igreja, x.idade, x.camisa, x.status, nomeS(x), nomeF(x), nomeV(x), nomeI(x)].map(v => '"' + String(v == null ? '' : v).replace(/"/g, '""') + '"').join(';'))); const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob(['﻿' + linhas.join('\n')], { type: 'text/csv;charset=utf-8' })); a.download = `top-${nome}-${hoje()}.csv`; a.click(); }

// ------------------------------------------------------------ painel
function topPainel(p, t) {
  const P = t.participantes; const n = P.filter(x => x.tipo === 'novato'), s = P.filter(x => x.tipo === 'servidor'), c = P.filter(x => x.tipo === 'coord');
  if (!P.length) return `<div class="card empty">Nenhum inscrito ainda. Importe a planilha do Legendários Global ou cadastre manualmente na aba <button class="link" onclick="go('top','importar')">Importar / cadastro</button>.</div>`;
  const pres = P.filter(x => x.status === 'PRESENTE').length; const bruto = P.reduce((a, x) => a + Number(x.valor || 0), 0);
  const porCid = {}; P.forEach(x => { const k = x.cidade || '—'; porCid[k] = (porCid[k] || 0) + 1; }); const cid = Object.entries(porCid).sort((a, b) => b[1] - a[1]).slice(0, 10);
  const inaptos = P.filter(x => x.saude && x.saude.avaliacao && x.saude.avaliacao !== 'Apto').length; const risco = n.filter(x => x.saude && x.saude.risco && x.saude.risco !== 'Baixo').length;
  return `<div class="kpis"><div class="kpi highlight"><div class="l">Inscritos</div><div class="v">${P.length}</div><div class="m">${n.length} novatos · ${s.length} servidores · ${c.length} coordenação</div></div>
    <div class="kpi"><div class="l">Credenciados</div><div class="v">${pres}</div><div class="m">${P.length - pres} ainda não</div></div>
    <div class="kpi clk" onclick="go('top','setores')"><div class="l">Servidores sem setor</div><div class="v">${s.concat(c).filter(x => !x.setorId).length}</div><div class="m">de ${s.length + c.length}</div></div>
    <div class="kpi clk" onclick="go('top','familias')"><div class="l">Novatos sem família</div><div class="v">${n.filter(x => !x.familiaId).length}</div><div class="m">${t.familias.length} família(s)</div></div>
    <div class="kpi clk" onclick="go('top','embarque')"><div class="l">Sem veículo</div><div class="v">${P.filter(x => !x.veiculoId).length}</div><div class="m">${t.veiculos.length} veículo(s)</div></div>
    <div class="kpi clk" onclick="go('top','oracao')"><div class="l">Novatos com menos de ${minInterc(t)} intercessores</div><div class="v">${semInterc(t, n).length}</div></div>
    <div class="kpi"><div class="l">Inscrições (bruto)</div><div class="v">${fmt(bruto)}</div><div class="m">${(S.inscritos || []).filter(i => i.projetoId === p.id).length} em Repasses de inscritos</div></div></div>
  <div class="grid g2"><div class="card"><div class="card-head"><div><h2>Setores — meta × alocados</h2><div class="sub">Entre parênteses: quantos pediram o setor como 1ª opção.</div></div><button class="s" onclick="go('top','setores')">Editar setores</button></div>
    <table class="compact"><tr><th>Setor</th><th>Coordena</th><th class="num">Meta</th><th class="num">Alocados</th><th style="width:120px"></th></tr>${t.setores.map(st => { const al = P.filter(x => x.setorId === st.id && x.tipo === 'servidor').length; const co = P.filter(x => x.setorId === st.id && x.tipo === 'coord'); const pedidos = s.filter(x => (x.prefs || [])[0] === st.nome).length; return `<tr><td><b>${esc(st.nome)}</b> <span class="mut sm">(${pedidos})</span></td><td class="sm">${co.length ? co.map(tpCurto).join(', ') : '<span class="pill warn">sem coord.</span>'}</td><td class="num">${st.meta || '—'}</td><td class="num">${al}</td><td><div class="bar"><i class="${st.meta && al > st.meta ? 'over' : ''}" style="width:${st.meta ? Math.min(100, al / st.meta * 100) : 0}%"></i></div></td></tr>`; }).join('')}</table></div>
  <div class="card"><div class="card-head"><div><h2>De onde vêm</h2><div class="sub">Base para o plano de embarque.</div></div></div><table class="compact"><tr><th>Cidade</th><th class="num">Total</th><th class="num">Novatos</th><th class="num">Servidores</th></tr>${cid.map(([ci, q]) => `<tr><td>${esc(ci)}</td><td class="num">${q}</td><td class="num">${n.filter(x => (x.cidade || '—') === ci).length}</td><td class="num">${q - n.filter(x => (x.cidade || '—') === ci).length}</td></tr>`).join('')}</table>
    <div class="al w" style="margin-top:12px"><b>Pendências</b> · ${inaptos} não apto(s) · ${risco} novato(s) com risco médio/alto · ${t.setores.filter(st => !P.some(x => x.setorId === st.id && x.tipo === 'coord')).length} setor(es) sem coordenador${t.veiculos.filter(v => v.cap && P.filter(x => x.veiculoId === v.id).length > v.cap).length ? ' · veículo(s) acima da lotação' : ''}</div></div></div>`;
}

// ------------------------------------------------------------ novatos / servidores
function topNovatos(p, t) {
  const ns = t.participantes.filter(x => x.tipo === 'novato'); const l = topFiltrar(t, ns); const ver = podeVerSaude(p);
  return topBarra(t, ns, { fam: true, novo: 'novato', csv: 'novatos' }) + `<div class="card"><div class="card-head"><div><h2>Novatos</h2><div class="sub">${l.length} de ${ns.length}${ver ? '' : ' · dados de saúde só na aba Saúde e resgate (acesso restrito)'}</div></div></div>
  ${l.length ? `<table class="compact"><tr><th>Nome</th><th>Idade</th><th>Cidade</th><th>Igreja</th><th>Família</th><th>Camisa</th><th>Cond.</th><th>Intercessor</th><th>Veículo</th><th>Situação</th><th></th></tr>${l.map(x => `<tr><td><b>${tpNome(x)}</b>${x.parente ? ' <span class="pill grey" title="' + esc(x.parente) + '">parente</span>' : ''}${x.saude && x.saude.risco && x.saude.risco !== 'Baixo' ? ' <span class="pill warn" title="ver Saúde">!</span>' : ''}<div class="desc">${esc(x.telefone || '')}${x.email ? ' · ' + esc(x.email) : ''}</div></td><td>${x.idade || ''}</td><td class="sm">${esc(x.cidade || '')}</td><td class="sm">${esc(x.igreja || '')}</td><td>${selFam(t, x)}</td><td>${esc(x.camisa || '')}</td><td title="condicionamento físico 1–5">${x.cond ? '●'.repeat(x.cond) + '<span class="mut">' + '○'.repeat(5 - x.cond) + '</span>' : ''}</td><td class="sm">${intercDe(x).length ? intercDe(x).map(id => tpCurto(tpById(t, id) || { nome: '?' })).join(', ') : ''}${intercDe(x).length < minInterc(t) ? ' <span class="pill warn">faltam ' + (minInterc(t) - intercDe(x).length) + '</span>' : ''}</td><td>${selVeic(t, x)}</td><td>${pillSit(x)} ${ver ? pillRisco(x) : ''}</td><td style="white-space:nowrap"><button class="s" onclick="popupParticipante('novato','${x.id}')">Editar</button></td></tr>`).join('')}</table>` : '<div class="empty">Nenhum novato no filtro.</div>'}</div>`;
}
function topServidores(p, t) {
  const ss = t.participantes.filter(x => x.tipo !== 'novato'); const l = topFiltrar(t, ss);
  return topBarra(t, ss, { setor: true, tipo: true, novo: 'servidor', csv: 'servidores' }) + `<div class="card"><div class="card-head"><div><h2>Servidores e coordenação</h2><div class="sub">${l.length} de ${ss.length} · o setor pode ser trocado direto na lista.</div></div></div>
  ${l.length ? `<table class="compact"><tr><th>Nome</th><th>Tipo</th><th>Cidade · sede</th><th>Já serviu</th><th>Preferências</th><th>Habilidade · veículo</th><th>Setor</th><th>Veículo</th><th>Situação</th><th></th></tr>${l.map(x => `<tr><td><b>${tpNome(x)}</b><div class="desc">${esc(x.telefone || '')}</div></td><td>${x.tipo === 'coord' ? '<span class="pill" style="background:var(--acc2);color:var(--acc)">coordenação</span>' : '<span class="pill grey">servidor</span>'}</td><td class="sm">${esc(x.cidade || '')}<div class="mut">${esc(x.sede || '')}</div></td><td class="sm">${esc(x.jaServiu || '')}${x.areasServiu ? '<div class="mut">' + esc(x.areasServiu) + '</div>' : ''}</td><td class="sm">${(x.prefs || []).join(' · ')}</td><td class="sm">${[x.habilidades, x.veiculoProprio ? '🚗 ' + x.veiculoProprio : ''].filter(Boolean).map(esc).join(' · ') || '—'}</td><td>${selSetor(t, x)}</td><td>${selVeic(t, x)}</td><td>${pillSit(x)}</td><td style="white-space:nowrap"><button class="s" onclick="popupParticipante('${x.tipo}','${x.id}')">Editar</button></td></tr>`).join('')}</table>` : '<div class="empty">Nenhum servidor no filtro.</div>'}</div>`;
}

// ------------------------------------------------------------ setores
function topSetores(p, t) {
  const P = t.participantes; const sem = P.filter(x => x.tipo !== 'novato' && !x.setorId); const ed = podeEditarTop(p);
  return `<div class="card"><div class="card-head"><div><h2>Setores</h2><div class="sub">Crie, renomeie e defina a meta de cada setor. Coordenação e servidores são alocados abaixo, na lista de Servidores ou pelo seletor de cada cartão.</div></div>${ed ? `<button class="p" onclick="popupSetor()">+ Setor</button>` : ''}</div>
  <div class="grid g3">${t.setores.map(st => { const al = P.filter(x => x.setorId === st.id); const co = al.filter(x => x.tipo === 'coord'), sv = al.filter(x => x.tipo === 'servidor'); return `<div class="box" style="padding:12px"><div class="flex"><strong>${esc(st.nome)}</strong><span class="right sm mut">${sv.length}${st.meta ? '/' + st.meta : ''} serv. · ${co.length} coord.</span></div><div class="bar" style="margin:6px 0"><i class="${st.meta && sv.length > st.meta ? 'over' : ''}" style="width:${st.meta ? Math.min(100, sv.length / st.meta * 100) : 0}%"></i></div><div>${co.map(x => `<span class="chip" style="background:var(--acc2)">★ ${tpCurto(x)} <button title="tirar do setor" onclick="topSet('${x.id}','setorId','')">✕</button></span>`).join('')}${sv.map(x => `<span class="chip">${tpCurto(x)} <button title="tirar do setor" onclick="topSet('${x.id}','setorId','')">✕</button></span>`).join('')}</div>
    <div class="flex" style="margin-top:8px"><select style="flex:1" onchange="if(this.value){topSet(this.value,'setorId','${st.id}')}"><option value="">+ adicionar pessoa…</option>${P.filter(x => x.tipo !== 'novato' && x.setorId !== st.id).sort((a, b) => a.nome.localeCompare(b.nome)).map(x => `<option value="${x.id}">${esc(x.nome)}${x.setorId ? ' (em ' + esc((t.setores.find(s => s.id === x.setorId) || {}).nome || '') + ')' : ''}</option>`).join('')}</select>${ed ? `<button class="s" onclick="popupSetor('${st.id}')">Editar</button>` : ''}</div></div>`; }).join('')}</div></div>
  <div class="card"><div class="card-head"><div><h2>Sem setor <span class="pill ${sem.length ? 'warn' : 'ok'}">${sem.length}</span></h2><div class="sub">Sugestão pela 1ª preferência informada na inscrição (se o setor existir e não estiver cheio, senão a 2ª).</div></div>${sem.length ? `<button class="s" onclick="topAlocarSugestoes()">Alocar todos pela sugestão</button>` : ''}</div>
  ${sem.length ? `<table class="compact"><tr><th>Nome</th><th>Tipo</th><th>Cidade</th><th>Já serviu</th><th>Preferências</th><th>Sugestão</th><th></th></tr>${sem.map(x => { const sug = topSugestao(t, x); return `<tr><td><b>${tpNome(x)}</b></td><td class="sm">${TOP_TIPOS[x.tipo]}</td><td class="sm">${esc(x.cidade || '')}</td><td class="sm">${esc(x.jaServiu || '')}${x.areasServiu ? ' · ' + esc(x.areasServiu) : ''}</td><td class="sm">${(x.prefs || []).join(' · ') || '—'}</td><td>${sug ? `<span class="pill ok">${esc(sug.nome)}</span>` : '<span class="mut sm">sem sugestão</span>'}</td><td class="flex" style="flex-wrap:nowrap">${sug ? `<button class="btn" onclick="topSet('${x.id}','setorId','${sug.id}')">Alocar</button>` : ''}${selSetor(t, x)}</td></tr>`; }).join('')}</table>` : '<div class="empty">Todos alocados.</div>'}</div>`;
}
function topSugestao(t, x) { const P = t.participantes; for (const pref of (x.prefs || [])) { const st = t.setores.find(s => s.nome.toLowerCase() === pref.toLowerCase()); if (!st) continue; const al = P.filter(y => y.setorId === st.id && y.tipo === 'servidor').length; if (!st.meta || al < st.meta) return st; } return null; }
function topAlocarSugestoes() { const p = topProjetoAtual(); const t = topDe(p.id); let n = 0; t.participantes.filter(x => x.tipo !== 'novato' && !x.setorId).forEach(x => { const s = topSugestao(t, x); if (s) { x.setorId = s.id; n++; } }); save(); render(); toast(n + ' alocado(s) pela preferência.'); }
function popupSetor(id) { const p = topProjetoAtual(); const t = topDe(p.id); const st = id ? t.setores.find(s => s.id === id) : { nome: '', meta: 0 }; popup(`<h2>${id ? 'Editar setor' : 'Novo setor'}</h2><div class="grid g2"><div><label>Nome *</label><input id="stNome" value="${esc(st.nome)}"></div><div><label>Meta de servidores</label><input id="stMeta" type="number" min="0" value="${st.meta || ''}" placeholder="0 = sem meta"></div></div><div class="flex" style="margin-top:14px"><button class="p" onclick="salvarSetor('${id || ''}')">Salvar</button>${id ? `<button class="d" onclick="removerSetor('${id}')">Remover</button>` : ''}<button class="s" onclick="fecharPopup()">Cancelar</button></div>`); setTimeout(() => document.getElementById('stNome').focus(), 30); }
function salvarSetor(id) { const p = topProjetoAtual(); const t = topDe(p.id); const nome = document.getElementById('stNome').value.trim(), meta = Number(document.getElementById('stMeta').value) || 0; if (!nome) return toast('Informe o nome.'); if (t.setores.some(s => s.id !== id && s.nome.toLowerCase() === nome.toLowerCase())) return toast('Já existe esse setor.'); if (id) Object.assign(t.setores.find(s => s.id === id), { nome, meta }); else t.setores.push({ id: uid(), nome, meta }); save(); popupHtml = null; render(); }
function removerSetor(id) { const p = topProjetoAtual(); const t = topDe(p.id); const n = t.participantes.filter(x => x.setorId === id).length; if (!confirm(`Remover o setor?${n ? ' ' + n + ' pessoa(s) ficarão sem setor.' : ''}`)) return; t.participantes.forEach(x => { if (x.setorId === id) x.setorId = null; }); t.setores = t.setores.filter(s => s.id !== id); save(); popupHtml = null; render(); }

// ------------------------------------------------------------ famílias
function topFamilias(p, t) {
  const ns = t.participantes.filter(x => x.tipo === 'novato'); const servs = t.participantes.filter(x => x.tipo !== 'novato'); const sem = ns.filter(x => !x.familiaId); const ed = podeEditarTop(p);
  const selPessoa = (fid, campo, atual) => `<select style="width:auto;padding:4px 6px;font-size:12px" onchange="famSet('${fid}','${campo}',this.value)"><option value="">— ${campo === 'paiId' ? 'Pai' : 'Padrinho'} —</option>${servs.sort((a, b) => a.nome.localeCompare(b.nome)).map(x => `<option value="${x.id}" ${atual === x.id ? 'selected' : ''}>${esc(x.nome)}</option>`).join('')}</select>`;
  return `<div class="card"><div class="card-head"><div><h2>Famílias</h2><div class="sub">Crie quantas famílias precisar (ou várias de uma vez), defina Pai e Padrinho e coloque cada novato na sua — pelo seletor do cartão, pela lista de Novatos, ou colando a lista de nomes que você recebe pronta.</div></div>${ed ? `<div class="flex"><button class="p" onclick="popupFamilia()">+ Família</button><button class="s" onclick="criarFamiliasEmLote()">Criar várias</button><button class="s" onclick="popupColarFamilias()">Colar lista pronta</button></div>` : ''}</div>
  ${t.familias.length ? `<div class="grid g3">${t.familias.map(f => { const m = ns.filter(x => x.familiaId === f.id); const mI = m.length ? Math.round(m.reduce((a, x) => a + Number(x.idade || 0), 0) / m.length) : 0; const mC = m.filter(x => x.cond).length ? (m.reduce((a, x) => a + Number(x.cond || 0), 0) / m.filter(x => x.cond).length).toFixed(1) : '—'; return `<div class="box" style="padding:12px"><div class="flex"><strong>${esc(f.nome)}</strong><span class="right pill grey">${m.length} novato(s)</span></div><div class="flex sm" style="margin:6px 0;gap:6px">${selPessoa(f.id, 'paiId', f.paiId)}${selPessoa(f.id, 'padrinhoId', f.padrinhoId)}</div><div class="sm mut">idade média ${mI || '—'} · condicionamento ${mC}</div><div style="margin-top:6px">${m.map(x => `<span class="chip">${tpCurto(x)}${x.saude && x.saude.risco && x.saude.risco !== 'Baixo' ? ' <b style="color:var(--warn)">!</b>' : ''} <button title="tirar da família" onclick="topSet('${x.id}','familiaId','')">✕</button></span>`).join('') || '<span class="sm mut">vazia</span>'}</div>
      <div class="flex" style="margin-top:8px"><select style="flex:1" onchange="if(this.value){topSet(this.value,'familiaId','${f.id}')}"><option value="">+ adicionar novato…</option>${ns.filter(x => x.familiaId !== f.id).sort((a, b) => a.nome.localeCompare(b.nome)).map(x => `<option value="${x.id}">${esc(x.nome)}${x.familiaId ? ' (' + esc((t.familias.find(g => g.id === x.familiaId) || {}).nome || '') + ')' : ''}</option>`).join('')}</select>${ed ? `<button class="s" onclick="popupFamilia('${f.id}')">Editar</button>` : ''}</div></div>`; }).join('')}</div>` : '<div class="empty">Nenhuma família ainda. Use "+ Família" ou "Criar várias".</div>'}</div>
  <div class="card"><div class="card-head"><div><h2>Novatos sem família <span class="pill ${sem.length ? 'warn' : 'ok'}">${sem.length}</span></h2></div>${sem.length && t.familias.length ? `<button class="s" onclick="distribuirFamilias()">Distribuir os restantes equilibrando idade e condicionamento</button>` : ''}</div>${sem.length ? `<table class="compact"><tr><th>Nome</th><th>Idade</th><th>Cidade</th><th>Cond.</th><th>Família</th></tr>${sem.map(x => `<tr><td>${tpNome(x)}</td><td>${x.idade || ''}</td><td class="sm">${esc(x.cidade || '')}</td><td>${x.cond || ''}</td><td>${selFam(t, x)}</td></tr>`).join('')}</table>` : ''}</div>`;
}
function famSet(fid, k, v) { const p = topProjetoAtual(); const t = topDe(p.id); const f = t.familias.find(x => x.id === fid); f[k] = v || null; save(); render(); }
function popupFamilia(id) { const p = topProjetoAtual(); const t = topDe(p.id); const f = id ? t.familias.find(x => x.id === id) : { nome: 'Família ' + (t.familias.length + 1) }; popup(`<h2>${id ? 'Editar família' : 'Nova família'}</h2><label>Nome *</label><input id="fmNome" value="${esc(f.nome)}"><label style="margin-top:8px">Observações</label><input id="fmObs" value="${esc(f.obs || '')}"><div class="flex" style="margin-top:14px"><button class="p" onclick="salvarFamilia('${id || ''}')">Salvar</button>${id ? `<button class="d" onclick="removerFamilia('${id}')">Remover</button>` : ''}<button class="s" onclick="fecharPopup()">Cancelar</button></div>`); }
function salvarFamilia(id) { const p = topProjetoAtual(); const t = topDe(p.id); const nome = document.getElementById('fmNome').value.trim(), obs = document.getElementById('fmObs').value.trim(); if (!nome) return toast('Informe o nome.'); if (id) Object.assign(t.familias.find(x => x.id === id), { nome, obs }); else t.familias.push({ id: uid(), nome, obs, paiId: null, padrinhoId: null }); save(); popupHtml = null; render(); }
function removerFamilia(id) { const p = topProjetoAtual(); const t = topDe(p.id); if (!confirm('Remover a família? Os novatos ficam sem família.')) return; t.participantes.forEach(x => { if (x.familiaId === id) x.familiaId = null; }); t.familias = t.familias.filter(x => x.id !== id); save(); popupHtml = null; render(); }
function criarFamiliasEmLote() { const p = topProjetoAtual(); const t = topDe(p.id); const n = Number(prompt('Quantas famílias criar?', '10')); if (!(n > 0)) return; const base = t.familias.length; for (let i = 1; i <= n; i++) t.familias.push({ id: uid(), nome: 'Família ' + (base + i), paiId: null, padrinhoId: null }); save(); render(); }
function distribuirFamilias() { const p = topProjetoAtual(); const t = topDe(p.id); const sem = t.participantes.filter(x => x.tipo === 'novato' && !x.familiaId).sort((a, b) => (Number(b.cond) || 3) - (Number(a.cond) || 3) || (Number(b.idade) || 0) - (Number(a.idade) || 0)); sem.forEach(x => { const alvo = t.familias.map(f => ({ f, n: t.participantes.filter(y => y.familiaId === f.id).length })).sort((a, b) => a.n - b.n)[0]; if (alvo) x.familiaId = alvo.f.id; }); save(); render(); }
function popupColarFamilias() { popup(`<h2>Colar lista pronta de famílias</h2><p class="sm mut">Cole no formato que você recebe: uma linha com o nome da família (ex.: <b>Família 3</b> ou <b>FAMÍLIA 3 - Pai: João</b>) seguida das linhas com os nomes dos novatos. O sistema encontra cada novato pelo nome (ignora acentos e maiúsculas) e cria a família se não existir. Nomes não encontrados são listados no final para você ajustar.</p><textarea id="clTxt" style="width:100%;height:260px;font-family:monospace;font-size:12px" placeholder="Família 1\nJoão da Silva\nPedro Souza\n\nFamília 2\n..."></textarea><div class="flex" style="margin-top:12px"><button class="p" onclick="aplicarColagem('familia')">Aplicar</button><button class="s" onclick="fecharPopup()">Cancelar</button></div>`); }
const normNome = (s) => String(s || '').normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase().replace(/[^a-z0-9 ]/g, ' ').replace(/\s+/g, ' ').trim();
function acharParticipante(t, nome, tipos) { const n = normNome(nome); if (!n) return null; const cand = t.participantes.filter(x => !tipos || tipos.includes(x.tipo)); return cand.find(x => normNome(x.nome) === n) || cand.find(x => normNome(x.nome).startsWith(n)) || cand.find(x => { const a = normNome(x.nome).split(' '), b = n.split(' '); return b.length >= 2 && a[0] === b[0] && a[a.length - 1] === b[b.length - 1]; }) || null; }
function aplicarColagem(modo) {
  const p = topProjetoAtual(); const t = topDe(p.id); const linhas = document.getElementById('clTxt').value.split('\n').map(l => l.trim()).filter(Boolean); let grupo = null; const naoAchados = []; let n = 0;
  const ehGrupo = (l) => modo === 'familia' ? /^fam[ií]lia\b/i.test(l) || /^fam\.?\s*\d+/i.test(l) : /^(caminh[aã]o|[oô]nibus|van|micro|ve[ií]culo|carro)\b/i.test(l) || /\d+\s*lugares/i.test(l);
  linhas.forEach(l => {
    if (ehGrupo(l)) { const nome = l.split(/\s[-–:]\s|:/)[0].trim(); if (modo === 'familia') { grupo = t.familias.find(f => normNome(f.nome) === normNome(nome)); if (!grupo) { grupo = { id: uid(), nome, paiId: null, padrinhoId: null }; t.familias.push(grupo); } const mPai = l.match(/pai\s*[:\-]\s*([^,;|]+)/i); if (mPai) { const pai = acharParticipante(t, mPai[1], ['servidor', 'coord']); if (pai) grupo.paiId = pai.id; } } else { grupo = t.veiculos.find(v => normNome(v.nome) === normNome(nome)); if (!grupo) { const cap = (l.match(/(\d+)\s*lugares/i) || [])[1]; grupo = { id: uid(), nome, cap: Number(cap) || 0, saida: '', resp: '' }; t.veiculos.push(grupo); } } return; }
    if (!grupo) return; const x = acharParticipante(t, l.replace(/^\d+[\.\)\-\s]+/, ''), modo === 'familia' ? ['novato'] : null); if (x) { x[modo === 'familia' ? 'familiaId' : 'veiculoId'] = grupo.id; n++; } else naoAchados.push(l);
  });
  save(); popupHtml = null; render(); if (naoAchados.length) popup(`<h2>${n} vinculado(s) · ${naoAchados.length} não encontrado(s)</h2><p class="sm mut">Confira a grafia ou cadastre a pessoa; depois cole só esses de novo.</p><ul class="sm" style="margin:8px 0 0 18px">${naoAchados.map(x => `<li>${esc(x)}</li>`).join('')}</ul><div class="flex" style="margin-top:12px"><button class="s" onclick="fecharPopup()">Fechar</button></div>`); else toast(n + ' vinculado(s).');
}

// ------------------------------------------------------------ embarque
function topEmbarque(p, t) {
  const P = t.participantes; const sem = P.filter(x => !x.veiculoId); const ed = podeEditarTop(p);
  return `<div class="card"><div class="card-head"><div><h2>Plano de embarque</h2><div class="sub">Cadastre os veículos (caminhão, ônibus, van, carro) com lotação, saída e responsável; depois direcione cada pessoa — pelo seletor do veículo, pelas listas, colando a lista pronta, ou distribuindo por cidade.</div></div>${ed ? `<div class="flex"><button class="p" onclick="popupVeiculo()">+ Veículo</button><button class="s" onclick="popupColarVeiculos()">Colar lista pronta</button>${sem.length && t.veiculos.length ? `<button class="s" onclick="distribuirPorCidade()">Distribuir por cidade</button>` : ''}</div>` : ''}</div>
  ${t.veiculos.length ? t.veiculos.map(v => { const ps = P.filter(x => x.veiculoId === v.id); const nov = ps.filter(x => x.tipo === 'novato').length; const cheio = v.cap && ps.length > v.cap; return `<div class="box" style="padding:12px;margin-bottom:10px"><div class="flex"><strong>${esc(v.nome)}</strong><span class="sm mut">${v.saida ? 'saída ' + esc(v.saida) : ''}${v.resp ? ' · responsável ' + esc(v.resp) : ''}${v.cidades ? ' · ' + esc(v.cidades) : ''}</span><span class="right pill ${cheio ? 'red' : 'ok'}">${ps.length}${v.cap ? '/' + v.cap : ''} lugares</span>${ed ? `<button class="s" onclick="popupVeiculo('${v.id}')">Editar</button>` : ''}<button class="s" onclick="imprimirVeiculo('${v.id}')">Lista</button><button class="p" style="padding:7px 11px" onclick="popupChamada('${v.id}')">Chamada${ps.some(x => x.embarcou) ? ` ${ps.filter(x => x.embarcou).length}/${ps.length}` : ''}</button></div>${v.cap ? `<div class="bar" style="margin:6px 0"><i class="${cheio ? 'over' : ''}" style="width:${Math.min(100, ps.length / v.cap * 100)}%"></i></div>` : ''}<div class="sm mut">${nov} novato(s) · ${ps.length - nov} servidor(es)/coord. · cidades: ${[...new Set(ps.map(x => x.cidade).filter(Boolean))].slice(0, 8).join(', ') || '—'}</div>
    <details style="margin-top:6px"><summary class="sm">ver / editar passageiros</summary><table class="compact" style="margin-top:6px"><tr><th>Nome</th><th>Tipo</th><th>Cidade</th><th>Telefone</th><th>Contato de emergência</th><th>Veículo</th></tr>${ps.map(x => `<tr><td>${tpNome(x)}</td><td class="sm">${TOP_TIPOS[x.tipo]}</td><td class="sm">${esc(x.cidade || '')}</td><td class="sm">${esc(x.telefone || '')}</td><td class="sm">${esc(x.contatoNome || '')}${x.contatoTel ? ' · ' + esc(x.contatoTel) : ''}</td><td>${selVeic(t, x)}</td></tr>`).join('')}</table>
    <div class="flex" style="margin-top:8px"><select style="flex:1" onchange="if(this.value){topSet(this.value,'veiculoId','${v.id}')}"><option value="">+ adicionar pessoa…</option>${P.filter(x => x.veiculoId !== v.id).sort((a, b) => a.nome.localeCompare(b.nome)).map(x => `<option value="${x.id}">${esc(x.nome)} · ${esc(x.cidade || '')}${x.veiculoId ? ' (em ' + esc((t.veiculos.find(w => w.id === x.veiculoId) || {}).nome || '') + ')' : ''}</option>`).join('')}</select></div></details></div>`; }).join('') : '<div class="empty">Nenhum veículo cadastrado.</div>'}</div>
  <div class="card"><div class="card-head"><div><h2>Sem veículo <span class="pill ${sem.length ? 'warn' : 'ok'}">${sem.length}</span></h2></div></div>${sem.length ? `<table class="compact"><tr><th>Nome</th><th>Tipo</th><th>Cidade</th><th>Veículo próprio</th><th>Veículo</th></tr>${sem.sort((a, b) => (a.cidade || '').localeCompare(b.cidade || '')).map(x => `<tr><td>${tpNome(x)}</td><td class="sm">${TOP_TIPOS[x.tipo]}</td><td class="sm">${esc(x.cidade || '')}</td><td class="sm">${esc(x.veiculoProprio || '')}</td><td>${selVeic(t, x)}</td></tr>`).join('')}</table>` : ''}</div>`;
}
// Chamada de embarque: marca quem já está a bordo (pensada para o celular do responsável, na hora da saída)
function popupChamada(vid) {
  const p = topProjetoAtual(); const t = topDe(p.id); const v = t.veiculos.find(x => x.id === vid); if (!v) return;
  const ps = t.participantes.filter(x => x.veiculoId === vid).sort((a, b) => (a.tipo === 'novato' ? 0 : 1) - (b.tipo === 'novato' ? 0 : 1) || a.nome.localeCompare(b.nome));
  const ab = ps.filter(x => x.embarcou).length; const falta = ps.filter(x => !x.embarcou);
  popup(`<h2>Chamada — ${esc(v.nome)}</h2><div class="sm mut" style="margin-bottom:8px">${v.saida ? 'saída ' + esc(v.saida) + ' · ' : ''}${v.resp ? 'resp. ' + esc(v.resp) + ' · ' : ''}<b style="color:${ab === ps.length && ps.length ? 'var(--ok)' : 'var(--ink)'}">${ab}/${ps.length} a bordo</b>${falta.length ? ` · faltam ${falta.length}` : ' · todos a bordo'}</div>
  <div class="bar" style="margin:0 0 10px"><i style="width:${ps.length ? ab / ps.length * 100 : 0}%"></i></div>
  <div class="slots">${ps.map(x => `<div class="slot ${x.embarcou ? 'ok' : ''}" style="cursor:pointer" onclick="topEmbarcou('${x.id}','${vid}')"><div class="ic">${x.embarcou ? '✓' : ''}</div><div class="who"><b>${esc(x.nome)}</b><small>${TOP_TIPOS[x.tipo]}${x.cidade ? ' · ' + esc(x.cidade) : ''}${x.telefone ? ' · ' + esc(x.telefone) : ''}${x.embarcou ? ' · a bordo ' + dt(x.embarcou.em) : ''}</small></div>${x.telefone && !x.embarcou ? `<a class="s" style="padding:6px 9px;text-decoration:none;border-radius:8px;border:1px solid var(--line)" href="tel:${esc(String(x.telefone).replace(/\D/g, ''))}" onclick="event.stopPropagation()">ligar</a>` : ''}</div>`).join('') || '<div class="empty">Ninguém alocado neste veículo.</div>'}</div>
  <div class="flex" style="margin-top:14px"><button class="s" onclick="fecharPopup()">Fechar</button>${ab ? `<button class="d right" onclick="if(confirm('Limpar a chamada deste veículo?')){topLimparChamada('${vid}')}">Limpar chamada</button>` : ''}</div>`);
}
function topEmbarcou(id, vid) { const p = topProjetoAtual(); const t = topDe(p.id); const x = t.participantes.find(y => y.id === id); if (!x) return; x.embarcou = x.embarcou ? null : { em: new Date().toISOString(), por: me().id }; save(); popupChamada(vid); }
function topLimparChamada(vid) { const p = topProjetoAtual(); const t = topDe(p.id); t.participantes.filter(x => x.veiculoId === vid).forEach(x => { x.embarcou = null; }); save(); popupChamada(vid); }
function popupVeiculo(id) { const p = topProjetoAtual(); const t = topDe(p.id); const v = id ? t.veiculos.find(x => x.id === id) : { nome: '', cap: 46, saida: '', resp: '', cidades: '' }; popup(`<h2>${id ? 'Editar veículo' : 'Novo veículo'}</h2><div class="grid g2"><div><label>Nome *</label><input id="vcNome" value="${esc(v.nome)}" placeholder="Caminhão 1 — Ijuí"></div><div><label>Lugares</label><input id="vcCap" type="number" min="0" value="${v.cap || ''}" placeholder="0 = sem limite"></div><div><label>Saída (local, data e hora)</label><input id="vcSaida" value="${esc(v.saida || '')}" placeholder="Renovo Ijuí · 23/04 06:00"></div><div><label>Responsável / motorista</label><input id="vcResp" value="${esc(v.resp || '')}"></div><div style="grid-column:1/-1"><label>Cidades atendidas (para distribuir por cidade)</label><input id="vcCid" value="${esc(v.cidades || '')}" placeholder="Ijuí, Panambi, Santo Augusto"></div></div><div class="flex" style="margin-top:14px"><button class="p" onclick="salvarVeiculo('${id || ''}')">Salvar</button>${id ? `<button class="d" onclick="removerVeiculo('${id}')">Remover</button>` : ''}<button class="s" onclick="fecharPopup()">Cancelar</button></div>`); setTimeout(() => document.getElementById('vcNome').focus(), 30); }
function salvarVeiculo(id) { const p = topProjetoAtual(); const t = topDe(p.id); const g = (k) => document.getElementById(k).value.trim(); const nome = g('vcNome'); if (!nome) return toast('Informe o nome.'); const dados = { nome, cap: Number(g('vcCap')) || 0, saida: g('vcSaida'), resp: g('vcResp'), cidades: g('vcCid') }; if (id) Object.assign(t.veiculos.find(x => x.id === id), dados); else t.veiculos.push({ id: uid(), ...dados }); save(); popupHtml = null; render(); }
function removerVeiculo(id) { const p = topProjetoAtual(); const t = topDe(p.id); if (!confirm('Remover o veículo? Os passageiros ficam sem veículo.')) return; t.participantes.forEach(x => { if (x.veiculoId === id) x.veiculoId = null; }); t.veiculos = t.veiculos.filter(x => x.id !== id); save(); popupHtml = null; render(); }
function distribuirPorCidade() { const p = topProjetoAtual(); const t = topDe(p.id); let n = 0; t.participantes.filter(x => !x.veiculoId).forEach(x => { const c = normNome(x.cidade); if (!c) return; const v = t.veiculos.find(v => (v.cidades || '').split(',').map(normNome).includes(c) && (!v.cap || t.participantes.filter(y => y.veiculoId === v.id).length < v.cap)); if (v) { x.veiculoId = v.id; n++; } }); save(); render(); toast(n + ' pessoa(s) distribuída(s) pela cidade; o resto fica para ajuste manual.'); }
function popupColarVeiculos() { popup(`<h2>Colar lista pronta de embarque</h2><p class="sm mut">Uma linha com o veículo (ex.: <b>Caminhão 1 - 40 lugares</b> ou <b>Ônibus Santa Maria</b>) seguida dos nomes. Veículo que não existir é criado (a lotação é lida se aparecer "N lugares").</p><textarea id="clTxt" style="width:100%;height:260px;font-family:monospace;font-size:12px" placeholder="Caminhão 1 - 40 lugares\nJoão da Silva\n..."></textarea><div class="flex" style="margin-top:12px"><button class="p" onclick="aplicarColagem('veiculo')">Aplicar</button><button class="s" onclick="fecharPopup()">Cancelar</button></div>`); }
function imprimirVeiculo(id) { const p = topProjetoAtual(); const t = topDe(p.id); const v = t.veiculos.find(x => x.id === id); const ps = t.participantes.filter(x => x.veiculoId === id).sort((a, b) => a.nome.localeCompare(b.nome)); popup(`<div class="flex noprint" style="margin-bottom:8px"><button class="p" onclick="print()">Imprimir</button><button class="s" onclick="fecharPopup()">Fechar</button></div><h2>${esc(S.config.nome)} — ${esc(p.nome)}</h2><h3>Lista de embarque · ${esc(v.nome)}</h3><p class="sm">${v.saida ? 'Saída: ' + esc(v.saida) + ' · ' : ''}${v.resp ? 'Responsável: ' + esc(v.resp) + ' · ' : ''}${ps.length}${v.cap ? '/' + v.cap : ''} lugares</p><table class="compact"><tr><th>#</th><th>Nome</th><th>Tipo</th><th>Cidade</th><th>Telefone</th><th>Contato de emergência</th><th>Ida</th><th>Volta</th></tr>${ps.map((x, i) => `<tr><td>${i + 1}</td><td>${tpNome(x)}</td><td>${TOP_TIPOS[x.tipo]}</td><td>${esc(x.cidade || '')}</td><td>${esc(x.telefone || '')}</td><td>${esc(x.contatoNome || '')}${x.contatoTel ? ' · ' + esc(x.contatoTel) : ''}</td><td>☐</td><td>☐</td></tr>`).join('')}</table>`); }

// ------------------------------------------------------------ lista de oração
function topOracao(p, t) {
  const ns = t.participantes.filter(x => x.tipo === 'novato'); const servs = t.participantes.filter(x => x.tipo !== 'novato').sort((a, b) => a.nome.localeCompare(b.nome)); const falt = semInterc(t, ns); const l = topFiltrar(t, ns); const min = minInterc(t);
  const carga = {}; ns.forEach(x => intercDe(x).forEach(id => carga[id] = (carga[id] || 0) + 1)); const semCarga = servs.filter(s => !carga[s.id]);
  return topBarra(t, ns, { fam: true, csv: 'oracao' }) + `<div class="card"><div class="card-head"><div><h2>Lista de oração (intercessão)</h2><div class="sub">Cada novato precisa de pelo menos <b>${min}</b> intercessores (servidores/coordenação) orando por ele antes, durante e depois do TOP. ${ns.length} novatos × ${min} = ${ns.length * min} vínculos; ${servs.length} servidores → cerca de ${servs.length ? Math.ceil(ns.length * min / servs.length) : '—'} novatos por servidor. ${falt.length ? `<span class="pill warn">${falt.length} novato(s) abaixo do mínimo</span>` : '<span class="pill ok">todos com o mínimo</span>'}${semCarga.length ? ` · <span class="pill grey">${semCarga.length} servidor(es) ainda sem novato</span>` : ''}</div></div><div class="flex"><label class="sm flex" style="margin:0">mínimo <input type="number" min="1" max="10" style="width:60px;padding:4px 6px" value="${min}" onchange="topConfig('minIntercessores',this.value)"></label>${falt.length ? `<button class="p" onclick="distribuirIntercessores()">Completar automaticamente</button>` : ''}<button class="s" onclick="imprimirOracao(false)">Imprimir por novato</button><button class="s" onclick="imprimirOracao('servidor')">Imprimir por servidor</button><button class="s" onclick="imprimirOracao(true)">Versão para o grupo</button></div></div>
  <table class="compact"><tr><th>Novato</th><th>Cidade</th><th>Família</th><th>Esposa / mãe</th><th>Motivos de oração</th><th>Intercessores</th></tr>${l.map(x => { const ids = intercDe(x); return `<tr><td><b>${tpNome(x)}</b></td><td class="sm">${esc(x.cidade || '')}</td><td class="sm">${esc((t.familias.find(f => f.id === x.familiaId) || {}).nome || '—')}</td><td class="sm">${esc(x.contatoNome || '')}</td><td><input value="${esc(x.motivos || '')}" placeholder="ex.: família, saúde, trabalho" onchange="topSet('${x.id}','motivos',this.value)"></td><td><div>${ids.map(id => `<span class="chip">${tpCurto(tpById(t, id) || { nome: '?' })} <button title="remover" onclick="topInterc('${x.id}','${id}',true)">✕</button></span>`).join('')}${ids.length < min ? `<span class="pill warn">faltam ${min - ids.length}</span>` : ''}</div><select style="margin-top:4px;width:100%" onchange="if(this.value){topInterc('${x.id}',this.value)}"><option value="">+ adicionar intercessor…</option>${servs.filter(s => !ids.includes(s.id)).map(s => `<option value="${s.id}">${esc(s.nome)}${carga[s.id] ? ' (' + carga[s.id] + ')' : ''}</option>`).join('')}</select></td></tr>`; }).join('')}</table></div>
  <div class="card"><div class="card-head"><div><h2>Por servidor</h2><div class="sub">Quantos novatos cada servidor tem para orar — para a lista individual que vai para cada um.</div></div></div><table class="compact"><tr><th>Servidor</th><th>Setor</th><th class="num">Novatos</th><th>Quem</th></tr>${servs.map(s => { const meus = ns.filter(x => intercDe(x).includes(s.id)); return `<tr><td>${tpNome(s)}</td><td class="sm">${esc((t.setores.find(st => st.id === s.setorId) || {}).nome || '')}</td><td class="num">${meus.length}</td><td class="sm">${meus.map(tpCurto).join(', ')}</td></tr>`; }).join('')}</table></div>`;
}
function topConfig(k, v) { const p = topProjetoAtual(); const t = topDe(p.id); t.config = t.config || {}; t.config[k] = v; save(); render(); }
function topInterc(novatoId, servId, remover) { const p = topProjetoAtual(); const t = topDe(p.id); const x = tpById(t, novatoId); let ids = intercDe(x); ids = remover ? ids.filter(i => i !== servId) : ids.concat(ids.includes(servId) ? [] : [servId]); x.intercessores = ids; delete x.intercessorId; save(); render(); }
function distribuirIntercessores() {
  const p = topProjetoAtual(); const t = topDe(p.id); const servs = t.participantes.filter(x => x.tipo !== 'novato'); if (!servs.length) return toast('Sem servidores cadastrados.'); const min = minInterc(t);
  const carga = {}; t.participantes.filter(x => x.tipo === 'novato').forEach(x => intercDe(x).forEach(id => carga[id] = (carga[id] || 0) + 1));
  t.participantes.filter(x => x.tipo === 'novato').forEach(x => { let ids = intercDe(x); while (ids.length < min) { const s = servs.filter(s => !ids.includes(s.id) && (s.familiaId !== x.familiaId || true)).sort((a, b) => (carga[a.id] || 0) - (carga[b.id] || 0) || a.nome.localeCompare(b.nome))[0]; if (!s) break; ids = ids.concat([s.id]); carga[s.id] = (carga[s.id] || 0) + 1; } x.intercessores = ids; delete x.intercessorId; });
  save(); render(); toast('Intercessores completados — cada novato com pelo menos ' + min + '.');
}
function imprimirOracao(modo) {
  const p = topProjetoAtual(); const t = topDe(p.id); const ns = t.participantes.filter(x => x.tipo === 'novato').sort((a, b) => a.nome.localeCompare(b.nome)); const servs = t.participantes.filter(x => x.tipo !== 'novato').sort((a, b) => a.nome.localeCompare(b.nome));
  let corpo;
  if (modo === true) corpo = `<p class="sm mut">Versão para divulgação: só primeiro nome e cidade.</p><p>${ns.map(x => esc(x.nome.split(' ')[0]) + ' (' + esc(x.cidade || '') + ')').join(' · ')}</p>`;
  else if (modo === 'servidor') corpo = servs.map(s => { const meus = ns.filter(x => intercDe(x).includes(s.id)); if (!meus.length) return ''; return `<div style="page-break-inside:avoid;margin-bottom:14px"><h3 style="margin:0 0 4px">${tpNome(s)}</h3><table class="compact"><tr><th>Novato</th><th>Cidade</th><th>Família</th><th>Esposa/mãe</th><th>Motivos</th></tr>${meus.map(x => `<tr><td>${tpNome(x)}</td><td>${esc(x.cidade || '')}</td><td>${esc((t.familias.find(f => f.id === x.familiaId) || {}).nome || '')}</td><td>${esc(x.contatoNome || '')}</td><td>${esc(x.motivos || '')}</td></tr>`).join('')}</table></div>`; }).join('');
  else corpo = `<table class="compact"><tr><th>Novato</th><th>Cidade</th><th>Família</th><th>Esposa/mãe</th><th>Motivos</th><th>Intercessores</th></tr>${ns.map(x => `<tr><td>${tpNome(x)}</td><td>${esc(x.cidade || '')}</td><td>${esc((t.familias.find(f => f.id === x.familiaId) || {}).nome || '')}</td><td>${esc(x.contatoNome || '')}</td><td>${esc(x.motivos || '')}</td><td>${intercDe(x).map(id => esc((tpById(t, id) || {}).nome || '')).join(' · ')}</td></tr>`).join('')}</table>`;
  popup(`<div class="flex noprint" style="margin-bottom:8px"><button class="p" onclick="print()">Imprimir</button><button class="s" onclick="fecharPopup()">Fechar</button></div><h2>${esc(p.nome)} — Lista de oração</h2>${corpo}`);
}

// ------------------------------------------------------------ saúde
function topSaude(p, t) {
  if (!podeVerSaude(p)) return `<div class="card"><h2>Saúde e resgate</h2><div class="al b">Acesso restrito. Quem vê: Presidente, Tesoureiro, Coordenador e ADM do projeto e as pessoas autorizadas pela coordenação (Resgate, Coordenação Geral). Peça a liberação.</div></div>`;
  const P = t.participantes; const at = P.filter(x => x.saude && (x.saude.condicao || x.saude.medicamento || x.saude.restricao || (x.saude.risco && x.saude.risco !== 'Baixo') || (x.saude.avaliacao && x.saude.avaliacao !== 'Apto'))); const l = topFiltrar(t, at);
  const usuarios = S.usuarios.filter(u => u.ativo);
  return topBarra(t, at, { tipo: true, fam: true, csv: 'saude' }) + `<div class="card"><div class="card-head"><div><h2>Saúde e resgate <span class="pill red">restrito</span></h2><div class="sub">${at.length} pessoa(s) com alguma observação de saúde na inscrição. Restrição alimentar também interessa à Alimentação.</div></div><div class="flex"><label class="sm" style="margin:0">Quem mais pode ver:</label><select onchange="if(this.value){topLiberarSaude(this.value)}"><option value="">+ autorizar usuário…</option>${usuarios.filter(u => !t.saudeAcesso.includes(u.id)).map(u => `<option value="${u.id}">${esc(u.nome)}</option>`).join('')}</select></div></div>
  <div class="sm" style="margin-bottom:8px">${t.saudeAcesso.map(id => `<span class="chip">${esc(nomeU(id))} <button onclick="topLiberarSaude('${id}',true)">✕</button></span>`).join('') || '<span class="mut">ninguém além dos padrões</span>'}</div>
  <div class="kpi3"><div class="kpi"><div class="l">Não aptos / a avaliar</div><div class="v">${P.filter(x => x.saude && x.saude.avaliacao && x.saude.avaliacao !== 'Apto').length}</div></div><div class="kpi"><div class="l">Uso de medicamento</div><div class="v">${P.filter(x => x.saude && x.saude.medicamento).length}</div></div><div class="kpi"><div class="l">Restrição alimentar</div><div class="v">${P.filter(x => x.saude && x.saude.restricao).length}</div></div></div>
  ${l.length ? `<table class="compact"><tr><th>Nome</th><th>Tipo</th><th>Idade</th><th>Família</th><th>Risco / avaliação</th><th>Condição médica</th><th>Medicamento</th><th>Restrição alimentar</th><th>Peso · altura</th><th>Contato de emergência</th><th>Providência</th></tr>${l.map(x => { const s = x.saude || {}; return `<tr><td><b>${tpNome(x)}</b></td><td class="sm">${TOP_TIPOS[x.tipo]}</td><td>${x.idade || ''}</td><td class="sm">${esc((t.familias.find(f => f.id === x.familiaId) || {}).nome || '')}</td><td>${pillRisco(x)}${s.obsAvaliador ? `<div class="desc">${esc(s.obsAvaliador)}</div>` : ''}</td><td class="sm">${esc(s.condicao || '')}</td><td class="sm">${esc(s.medicamento || '')}</td><td class="sm">${esc(s.restricao || '')}</td><td class="sm">${s.peso ? s.peso + ' kg' : ''}${s.altura ? ' · ' + s.altura + ' cm' : ''}</td><td class="sm">${esc(x.contatoNome || '')}${x.contatoTel ? '<br>' + esc(x.contatoTel) : ''}</td><td><input value="${esc(s.providencia || '')}" placeholder="ex.: kit no Resgate" onchange="topSetSaude('${x.id}','providencia',this.value)"></td></tr>`; }).join('')}</table>` : '<div class="empty">Ninguém com observação de saúde no filtro.</div>'}
  <div class="al w" style="margin-top:10px">LGPD: estes dados existem só para a segurança do evento. Combine com a coordenação o prazo para apagá-los depois do TOP (botão "Apagar dados de saúde" na aba Importar / cadastro).</div></div>`;
}
function topLiberarSaude(uid_, remover) { const p = topProjetoAtual(); if (!podeVerSaude(p)) return; const t = topDe(p.id); t.saudeAcesso = remover ? t.saudeAcesso.filter(x => x !== uid_) : t.saudeAcesso.concat([uid_]); save(); render(); }
function topSetSaude(id, k, v) { const p = topProjetoAtual(); const t = topDe(p.id); const x = tpById(t, id); x.saude = x.saude || {}; x.saude[k] = v; save(); }

// ------------------------------------------------------------ cadastro manual
function popupParticipante(tipo, id) {
  const p = topProjetoAtual(); const t = topDe(p.id); const x = id ? tpById(t, id) : { tipo, saude: {} }; const s = x.saude || {}; const ver = podeVerSaude(p);
  popup(`<h2>${id ? 'Editar' : 'Novo'} ${TOP_TIPOS[x.tipo].toLowerCase()}</h2><div class="grid g3">
    <div style="grid-column:span 2"><label>Nome *</label><input id="ppNome" value="${esc(x.nome || '')}"></div><div><label>Tipo</label><select id="ppTipo">${Object.entries(TOP_TIPOS).map(([k, v]) => `<option value="${k}" ${x.tipo === k ? 'selected' : ''}>${v}</option>`).join('')}</select></div>
    <div><label>Telefone</label><input id="ppTel" value="${esc(x.telefone || '')}"></div><div><label>E-mail</label><input id="ppEmail" value="${esc(x.email || '')}"></div><div><label>Idade</label><input id="ppIdade" type="number" value="${x.idade || ''}"></div>
    <div><label>Cidade</label><input id="ppCid" value="${esc(x.cidade || '')}"></div><div><label>Sede / Track</label><input id="ppSede" value="${esc(x.sede || '')}"></div><div><label>Igreja</label><input id="ppIgr" value="${esc(x.igreja || '')}"></div>
    <div><label>Camisa</label><input id="ppCam" value="${esc(x.camisa || '')}"></div><div><label>Condicionamento (1–5)</label><input id="ppCond" type="number" min="1" max="5" value="${x.cond || ''}"></div><div><label>Valor da inscrição</label><input id="ppVal" type="number" step="0.01" value="${x.valor || ''}"></div>
    <div><label>Contato de emergência (esposa/mãe)</label><input id="ppCN" value="${esc(x.contatoNome || '')}"></div><div><label>Telefone do contato</label><input id="ppCT" value="${esc(x.contatoTel || '')}"></div><div><label>Situação</label><select id="ppSit"><option value="INSCRITO" ${x.status !== 'PRESENTE' ? 'selected' : ''}>inscrito</option><option value="PRESENTE" ${x.status === 'PRESENTE' ? 'selected' : ''}>credenciado</option></select></div>
    <div style="grid-column:span 3"><label>Já serviu / áreas / preferências (servidores)</label><input id="ppPref" value="${esc((x.prefs || []).join(', '))}" placeholder="Segurança, Logística"></div>
    <div style="grid-column:span 3"><label>Habilidades · veículo próprio · observações</label><input id="ppObs" value="${esc(x.obs || '')}"></div>
    ${ver ? `<div style="grid-column:1/-1"><label>Saúde (restrito)</label><div class="grid g3"><input id="ppCond2" value="${esc(s.condicao || '')}" placeholder="condição médica"><input id="ppMed" value="${esc(s.medicamento || '')}" placeholder="medicamento"><input id="ppRes" value="${esc(s.restricao || '')}" placeholder="restrição alimentar"></div></div>` : ''}</div>
    <div class="flex" style="margin-top:14px"><button class="p" onclick="salvarParticipante('${id || ''}')">Salvar</button>${id ? `<button class="d" onclick="removerParticipante('${id}')">Remover</button>` : ''}<button class="s" onclick="fecharPopup()">Cancelar</button></div>`);
  setTimeout(() => document.getElementById('ppNome').focus(), 30);
}
function salvarParticipante(id) {
  const p = topProjetoAtual(); const t = topDe(p.id); const g = (k) => { const el = document.getElementById(k); return el ? el.value.trim() : ''; }; const nome = g('ppNome'); if (!nome) return toast('Informe o nome.');
  const x = id ? tpById(t, id) : { id: uid(), criadoEm: agora(), quem: me().id, saude: {} };
  Object.assign(x, { nome, tipo: g('ppTipo'), telefone: g('ppTel'), email: g('ppEmail'), idade: Number(g('ppIdade')) || null, cidade: g('ppCid'), sede: g('ppSede'), igreja: g('ppIgr'), camisa: g('ppCam'), cond: Number(g('ppCond')) || null, valor: Number(g('ppVal')) || 0, contatoNome: g('ppCN'), contatoTel: g('ppCT'), status: g('ppSit'), prefs: g('ppPref').split(',').map(s => s.trim()).filter(Boolean), obs: g('ppObs') });
  if (document.getElementById('ppCond2')) { x.saude = x.saude || {}; x.saude.condicao = g('ppCond2'); x.saude.medicamento = g('ppMed'); x.saude.restricao = g('ppRes'); }
  if (!id) t.participantes.push(x); save(); popupHtml = null; render();
}
function removerParticipante(id) { const p = topProjetoAtual(); const t = topDe(p.id); if (!confirm('Remover esta pessoa da gestão do TOP?')) return; t.participantes = t.participantes.filter(x => x.id !== id); t.participantes.forEach(x => { if (x.intercessores) x.intercessores = x.intercessores.filter(i => i !== id); if (x.intercessorId === id) x.intercessorId = null; }); save(); popupHtml = null; render(); }

// ------------------------------------------------------------ importação da planilha do Legendários Global
function topImportar(p, t) {
  const ed = podeEditarTop(p); const semRep = t.participantes.filter(x => x.valor > 0 && !(S.inscritos || []).some(i => i.projetoId === p.id && (i.numero === x.transacao || normNome(i.nome) === normNome(x.nome)))).length;
  return `<div class="card"><div class="card-head"><div><h2>Importar planilha do Legendários Global</h2><div class="sub">Exporte o <b>relatório de participantes</b> (.xlsx) no site do Global e solte aqui. O sistema separa novatos, servidores e coordenação pelo ingresso, atualiza quem já existe (pela transação/CPF) sem duplicar e mantém as alocações já feitas.</div></div></div>
  ${ed ? `<div style="border:2px dashed var(--line);border-radius:14px;padding:26px;text-align:center;color:var(--mut)" ondragover="event.preventDefault();this.style.borderColor='var(--acc)'" ondragleave="this.style.borderColor='var(--line)'" ondrop="event.preventDefault();this.style.borderColor='var(--line)';topLerPlanilha(event.dataTransfer.files[0])">Solte a planilha aqui ou <label class="s" style="cursor:pointer">escolher arquivo<input type="file" accept=".xlsx,.xls,.csv" hidden onchange="topLerPlanilha(this.files[0])"></label><div id="impInfo" class="sm" style="margin-top:8px"></div></div>` : '<div class="al w">Só a coordenação do projeto, Tesoureiro ou Presidente importam.</div>'}
  <table class="compact" style="margin-top:14px"><tr><th>Coluna da planilha</th><th>Vira no sistema</th><th>Quem vê</th></tr>
  <tr><td>Ingresso · Top para quem · Valor Bilhete · ID Transação</td><td>Tipo (novato/servidor/coordenação), valor e nº para <b>Repasses de inscritos</b></td><td>todos · ADM</td></tr>
  <tr><td>Nome, Telefone, E-mail, Cidade, Sede, Igreja, Idade, Profissão</td><td>Cadastro, embarque, comunicação</td><td>coordenação e setores</td></tr>
  <tr><td>Status / Data credenciamento</td><td>Credenciado ou não</td><td>todos</td></tr>
  <tr><td>Família, Tamanho camisa, Condicionamento físico</td><td>Famílias, camisetas, balanceamento</td><td>coordenação, Logística</td></tr>
  <tr><td>Já serviu, Áreas já serviu / pretende servir, Habilidades, Veículo</td><td>Sugestão de setor, motoristas e recursos</td><td>coordenação</td></tr>
  <tr><td>Nome / telefone da esposa ou mãe, Nome/WhatsApp para contato</td><td>Contato de emergência e lista de oração</td><td>Intercessão, Resgate, Segurança</td></tr>
  <tr><td>Condição médica, Medicamento, Restrição alimentar, Peso, Altura, Risco, Avaliação</td><td>Saúde e resgate (restrito)</td><td>autorizados</td></tr>
  <tr><td>CPF, RG, Data de nascimento, Termo</td><td><b>Não importados</b> (CPF vira só um código para evitar duplicidade)</td><td>—</td></tr></table></div>
  <div class="card"><div class="card-head"><div><h2>Ligação com a tesouraria</h2><div class="sub">Cada inscrito com valor vira um registro em Projetos → Repasses de inscritos (novato/servidor/coordenador, valor bruto), onde você lança o repasse do Global quando o dinheiro entra.</div></div>${semRep ? `<button class="p" onclick="topEnviarRepasses()">Enviar ${semRep} inscrito(s) para Repasses</button>` : '<span class="pill ok">tudo enviado</span>'}</div></div>
  <div class="card"><div class="card-head"><div><h2>Histórico de importações</h2></div>${t.participantes.length && podeVerSaude(p) ? `<button class="d" onclick="topApagarSaude()">Apagar dados de saúde (após o TOP)</button>` : ''}</div>${t.importacoes.length ? `<table class="compact"><tr><th>Quando</th><th>Quem</th><th>Arquivo</th><th class="num">Novos</th><th class="num">Atualizados</th><th class="num">Sumiram da planilha</th></tr>${t.importacoes.slice().reverse().map(i => `<tr><td>${dt(i.em)}</td><td>${esc(nomeU(i.quem))}</td><td class="sm">${esc(i.arquivo)}</td><td class="num">${i.novos}</td><td class="num">${i.atualizados}</td><td class="num">${i.removidos}</td></tr>`).join('')}</table>` : '<div class="empty">Nenhuma importação.</div>'}</div>`;
}
function topLerPlanilha(f) {
  if (!f) return; const info = document.getElementById('impInfo'); if (!window.XLSX) { info.innerHTML = '<span style="color:var(--bad)">Leitor de planilha não carregou (sem internet?). Tente de novo com conexão.</span>'; return; }
  info.textContent = 'Lendo ' + f.name + '…'; const r = new FileReader();
  r.onload = () => { try { const wb = XLSX.read(r.result, { type: 'array' }); const ws = wb.Sheets[wb.SheetNames[0]]; const rows = XLSX.utils.sheet_to_json(ws, { defval: null, raw: false }); topAplicarPlanilha(rows, f.name, info); } catch (e) { info.innerHTML = '<span style="color:var(--bad)">Erro ao ler: ' + esc(e.message) + '</span>'; } };
  r.readAsArrayBuffer(f);
}
function topAplicarPlanilha(rows, arquivo, info) {
  const p = topProjetoAtual(); const t = topDe(p.id); const g = (r, ...ks) => { for (const k of ks) { const kk = Object.keys(r).find(x => normNome(x) === normNome(k)); if (kk && r[kk] != null && String(r[kk]).trim() !== '') return String(r[kk]).trim(); } return ''; };
  const numBR = (s) => Number(String(s || '').replace(/\./g, '').replace(',', '.')) || 0; const sim = (s) => s && /^sim/i.test(s) ? s : (s && !/^n[aã]o/i.test(s) ? s : '');
  let novos = 0, atualizados = 0; const vistos = new Set();
  rows.forEach(r => {
    const nome = g(r, 'Nome'); if (!nome) return; const ingresso = g(r, 'Ingresso'), paraQuem = g(r, 'Top para quem'), transacao = g(r, 'ID Transação'), cpf = g(r, 'CPF').replace(/\D/g, '');
    const tipo = /coordena/i.test(ingresso) ? 'coord' : /servir/i.test(ingresso) ? 'servidor' : /senderista/i.test(paraQuem) ? 'novato' : (numBR(g(r, 'Valor Bilhete')) > 1000 ? 'novato' : 'servidor');
    const cpfHash = cpf ? (typeof sha256 === 'function' ? sha256('cpf|' + cpf).slice(0, 16) : cpf.slice(-4)) : '';
    let x = t.participantes.find(y => (transacao && y.transacao === transacao) || (cpfHash && y.cpfHash === cpfHash)) || t.participantes.find(y => normNome(y.nome) === normNome(nome) && !y.transacao);
    const areasPref = g(r, 'Quais áreas pretende servir').split(',').map(s => s.trim()).filter(Boolean);
    const dados = { nome, tipo, transacao, cpfHash, email: g(r, 'Email'), telefone: g(r, 'Telefone'), cidade: g(r, 'Cidade que reside'), sede: g(r, 'Sede que faz parte'), igreja: g(r, 'Igreja que Frequenta'), profissao: g(r, 'Profissão'), idade: Number(g(r, 'Idade')) || null, camisa: g(r, 'Tamanho camisa'), cond: Number(g(r, 'Condicionamento físico')) || null, valor: numBR(g(r, 'Valor Bilhete')), status: /presente/i.test(g(r, 'Status')) || g(r, 'Data credenciamento') ? 'PRESENTE' : 'INSCRITO', credenciadoEm: g(r, 'Data credenciamento'), jaServiu: g(r, 'Você já serviu antes'), areasServiu: g(r, 'Quais áreas já serviu'), prefs: areasPref, habilidades: g(r, 'Habilidades'), veiculoProprio: sim(g(r, 'Tem veículo')) ? g(r, 'Descrição do veículo') || 'sim' : '', parente: sim(g(r, 'Participa algum parente')) ? g(r, 'Parente') || 'sim' : '', contatoNome: g(r, 'Nome esposa ou mãe', 'Nome para contato'), contatoTel: g(r, 'Telefone da esposa ou mãe', 'Whatsapp para contato'), familiaPlanilha: g(r, 'Família'), importadoEm: agora() };
    const saude = { condicao: sim(g(r, 'Condição médica')), medicamento: sim(g(r, 'Faz uso de medicamento')), restricao: sim(g(r, 'Tem restrição alimentar')), peso: g(r, 'Peso'), altura: g(r, 'Altura'), risco: g(r, 'riscoParticipante'), avaliacao: g(r, 'statusAvaliacaoParticipante'), obsAvaliador: g(r, 'observacaoFeitaPeloAvaliadorParticipante') };
    if (x) { Object.assign(x, dados); x.saude = { ...(x.saude || {}), ...saude }; atualizados++; } else { x = { id: uid(), ...dados, saude, setorId: null, familiaId: null, veiculoId: null, intercessores: [] }; t.participantes.push(x); novos++; }
    vistos.add(x.id);
    // família vinda da planilha (número) → cria/usa "Família N" se o novato ainda não tem
    if (x.tipo === 'novato' && !x.familiaId && x.familiaPlanilha) { const nomeF = 'Família ' + x.familiaPlanilha; let f = t.familias.find(y => normNome(y.nome) === normNome(nomeF)); if (!f) { f = { id: uid(), nome: nomeF, paiId: null, padrinhoId: null }; t.familias.push(f); } x.familiaId = f.id; }
  });
  const sumiram = t.participantes.filter(x => x.transacao && !vistos.has(x.id) && !x.cancelado); sumiram.forEach(x => { x.cancelado = agora(); });
  t.familias.sort((a, b) => a.nome.localeCompare(b.nome, 'pt', { numeric: true }));
  t.importacoes.push({ em: agora(), quem: me().id, arquivo, novos, atualizados, removidos: sumiram.length, linhas: rows.length });
  save(); render(); toast(`Importação: ${novos} novo(s), ${atualizados} atualizado(s)${sumiram.length ? ', ' + sumiram.length + ' marcado(s) como cancelado(s)' : ''}.`);
}
function topEnviarRepasses() { const p = topProjetoAtual(); const t = topDe(p.id); S.inscritos = S.inscritos || []; let n = 0; t.participantes.filter(x => x.valor > 0 && !x.cancelado).forEach(x => { if (S.inscritos.some(i => i.projetoId === p.id && (i.numero === x.transacao || normNome(i.nome) === normNome(x.nome)))) return; S.inscritos.push({ id: uid(), projetoId: p.id, nome: x.nome, numero: x.transacao || '', tipo: x.tipo === 'coord' ? 'coordenador' : x.tipo, bruto: x.valor, deducao: 0, liquido: x.valor, contato: x.telefone || '', obs: 'importado da Gestão do TOP', quem: me().id, criadoEm: agora() }); n++; }); save(); render(); toast(n + ' inscrito(s) enviado(s) para Repasses. Ajuste a dedução (royalties) lá antes de lançar.'); }
function topApagarSaude() { const p = topProjetoAtual(); const t = topDe(p.id); if (prompt('Isto apaga condição médica, medicamentos, restrições, peso, altura e avaliação de TODOS os inscritos deste TOP. Digite APAGAR para confirmar:') !== 'APAGAR') return; t.participantes.forEach(x => { x.saude = {}; }); t.saudeApagadoEm = agora(); t.saudeApagadoPor = me().id; save(); render(); toast('Dados de saúde apagados.'); }

// ------------------------------------------------------------ linha do tempo (página própria embutida; grava no projeto)
window.lgndTimelineGet = () => { const p = topProjetoAtual(); return p ? (topDe(p.id).linhaTempo || null) : null; };
window.lgndTimelineSet = (st) => { const p = topProjetoAtual(); if (!p) return; topDe(p.id).linhaTempo = st; save(); };
function topLinha(p, t) {
  const ini = window.LGND_DADOS_INICIAIS; const atual = t.linhaTempo; const nomeAtual = atual && atual.meta ? atual.meta.nome : null; const ehPadrao = nomeAtual === 'TOP RS 0426';
  return `<div class="card" style="padding:0;overflow:hidden"><div class="flex noprint" style="padding:10px 14px;border-bottom:1px solid var(--line)"><div><strong>Linha do tempo — ${esc(p.nome)}</strong><div class="sm mut">Paradas, trechos, atividades e setores em cada ponto. Salva junto com o projeto${typeof ONLINE !== 'undefined' && ONLINE ? ' e sincroniza online' : ''}. ${atual ? `Gravada: <b>${esc(nomeAtual || '')}</b> · ${(atual.paradas || []).length} parada(s)` : 'Ainda sem linha do tempo neste projeto.'}${ehPadrao && ini ? ' <span class="pill warn">é o modelo padrão de fábrica</span>' : ''}</div></div><span class="right"></span>${ini && podeEditarTop(p) && (!atual || nomeAtual !== ini.meta.nome) ? `<button class="p" onclick="topCarregarLinhaInicial('${p.id}')">Carregar ${esc(ini.meta.nome)} (${ini.paradas.length} paradas)</button>` : ''}<a class="s" href="linha_do_tempo_top.html" target="_blank" style="text-decoration:none">Abrir em tela cheia</a></div>
  <iframe src="linha_do_tempo_top.html?p=${encodeURIComponent(p.id)}" style="width:100%;height:calc(100vh - 190px);border:0;display:block"></iframe></div>`;
}
function topCarregarLinhaInicial(pid) { const ini = window.LGND_DADOS_INICIAIS; if (!ini) return toast('Conteúdo inicial não carregado.'); const t = topDe(pid); if (t.linhaTempo && t.linhaTempo.meta && t.linhaTempo.meta.nome !== 'TOP RS 0426' && !confirm(`Substituir a linha do tempo gravada ("${t.linhaTempo.meta.nome}") por "${ini.meta.nome}"? Exporte um .json antes se quiser guardar a atual.`)) return; t.linhaTempo = JSON.parse(JSON.stringify(ini)); save(); render(); toast('Linha do tempo "' + ini.meta.nome + '" carregada no projeto.'); }
